substitutions:
  _REGION: europe-southwest1
  _REPOSITORY: etiquetas-prom
  _IMAGE: email-worker
  _JOB: etiquetas-prom-email-worker
  _RUNTIME_SERVICE_ACCOUNT: cloud-run-campaign-worker@etiquetas-prom-prod.iam.gserviceaccount.com

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.cloudrun-worker
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$SHORT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$SHORT_SHA

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - jobs
      - deploy
      - ${_JOB}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$SHORT_SHA
      - --region
      - ${_REGION}
      - --service-account
      - ${_RUNTIME_SERVICE_ACCOUNT}
      - --tasks
      - "1"
      - --parallelism
      - "1"
      - --max-retries
      - "0"
      - --task-timeout
      - "15m"
      - --cpu
      - "1"
      - --memory
      - "2Gi"

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$SHORT_SHA
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest

options:
  logging: CLOUD_LOGGING_ONLY